import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import Main from '../components/Main'
import Personality from '../components/Personality'
import Powers from '../components/Powers'
import Why from '../components/Why'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Chico Vicente | Sovtech Grad Program</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Main />
      <Personality />
      <Powers />
      <Why />
    

      
      
    </div>
  )
}
